use sc_service::ChainType;
use solochain_template_runtime::WASM_BINARY;

/// Specialized `ChainSpec`. This is a specialization of the general Substrate ChainSpec type.
pub type ChainSpec = sc_service::GenericChainSpec;

/// Groth16Transfer verifying key generated by `generate-testnet-setup`.
///
/// V-03: single-party trusted setup — acceptable for testnet.
/// Run `cargo run --bin generate-testnet-setup` to regenerate and replace this file.
/// MPC ceremony required before mainnet.
const TRANSFER_CIRCUIT_VK: &[u8] = include_bytes!("../res/transfer_circuit.vk");

/// Empty 32-deep Poseidon Merkle root (all 2^32 leaves zero).
///
/// Computed by: z[0] = [0u8;32]; z[i] = Poseidon(z[i-1], z[i-1]); root = z[32].
/// Validated against the output of `generate-testnet-setup`.
const EMPTY_POSEIDON_ROOT_32: [u8; 32] = [
	0xd9, 0xea, 0x34, 0x97, 0x4c, 0x18, 0x8e, 0xac,
	0xd5, 0x19, 0xb1, 0x2a, 0x92, 0xb9, 0x60, 0xd5,
	0x1e, 0x55, 0xf5, 0xdf, 0x61, 0x6c, 0x7a, 0xa1,
	0x42, 0x7e, 0x25, 0x8e, 0xc5, 0xa1, 0x68, 0x2f,
];

pub fn development_chain_spec() -> Result<ChainSpec, String> {
	Ok(ChainSpec::builder(
		WASM_BINARY.ok_or_else(|| "Development wasm not available".to_string())?,
		None,
	)
	.with_name("Development")
	.with_id("dev")
	.with_chain_type(ChainType::Development)
	.with_genesis_config_preset_name(sp_genesis_builder::DEV_RUNTIME_PRESET)
	.build())
}

pub fn local_chain_spec() -> Result<ChainSpec, String> {
	Ok(ChainSpec::builder(
		WASM_BINARY.ok_or_else(|| "Development wasm not available".to_string())?,
		None,
	)
	.with_name("Local Testnet")
	.with_id("local_testnet")
	.with_chain_type(ChainType::Local)
	.with_genesis_config_preset_name(sp_genesis_builder::LOCAL_TESTNET_RUNTIME_PRESET)
	.build())
}

/// Production testnet chain spec.
///
/// Validators: Charlie + Dave (Aura/GRANDPA).  Sudo: Eve.
/// The Groth16Transfer VK and the empty 32-deep Poseidon Merkle root are
/// both embedded in genesis — no additional sudo transactions required.
///
/// Start with: `zerochain-node --chain testnet`
pub fn testnet_chain_spec() -> Result<ChainSpec, String> {
	let genesis = solochain_template_runtime::genesis_config_presets::production_testnet_genesis(
		TRANSFER_CIRCUIT_VK.to_vec(),
		EMPTY_POSEIDON_ROOT_32,
	);

	Ok(ChainSpec::builder(
		WASM_BINARY.ok_or_else(|| "Testnet WASM binary not available".to_string())?,
		None,
	)
	.with_name("ZeroChain Testnet")
	.with_id("zerochain_testnet")
	.with_chain_type(ChainType::Live)
	.with_genesis_config_patch(genesis)
	.build())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Guards against a transcription error in EMPTY_POSEIDON_ROOT_32.
    ///
    /// Recomputes z[0]=[0u8;32], z[i]=Poseidon(z[i-1],z[i-1]) for 32 rounds using
    /// the live production Poseidon (BN254 x5 t=3, iden3 parameters) and asserts
    /// the result matches the hardcoded genesis constant.  A wrong constant would
    /// make every initial transfer proof fail at the Merkle-path check.
    #[test]
    fn empty_poseidon_root_32_matches_computed() {
        let computed = zc_crypto::merkle::empty_root_depth(32);
        assert_eq!(
            computed,
            EMPTY_POSEIDON_ROOT_32,
            "EMPTY_POSEIDON_ROOT_32 constant (0x{}) does not match the \
             real Poseidon depth-32 empty root (0x{}). \
             Re-run generate-testnet-setup and update the constant.",
            hex::encode(EMPTY_POSEIDON_ROOT_32),
            hex::encode(computed),
        );
    }
}
